spring:
  application:
    name: app

  profiles:
    active: ${APP_ENV:prod}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none